### ISSUE TITLE
Error in runing runBBKNN function

### ISSUE THREAD

**Issue by Dragonlongzhilin** [compbiomed/singleCellTK#613] opened 2022-08-18 06:43 UTC
Thanks for developing a nice tool!
I encountered a problem when I correct the batch effect with the runBBKNN method.

The following code I used:
g <- singleCellTK::runBBKNN(a, useAssay="logcounts", batch = "orig.ident", nComponents=50)

object a is :
![image](https://user-images.githubusercontent.com/33304280/185314747-37bcbeef-1e5d-4a21-8abb-1595e89a1f58.png)

error is:
![image](https://user-images.githubusercontent.com/33304280/185314569-a1dc744e-392a-4cd4-a7f7-a311fe6d75b9.png)

How to solve this problem?

**Comment by mvfki** [comment] 2022-08-18 12:06
Hi there,

Thanks a lot for trying out our tool. The problem is your R could not find an active Python BBKNN module. There are possible reasons for it: a) you haven't installed Python b) you've got Python installed but haven't install BBKNN c) everything about Python is ok but your R configuration fail to find it. If the first one was the reason, please follow the message at the bottom of your screenshot as that is the fastest method. If it's about the next two, please get back to us and I'll try to help you out with more information. 

There are online documentation about this problem which might be helpful also. 
[https://camplab.net/sctk/v2.7.1/articles/installation.html#install-python-dependencies](https://camplab.net/sctk/v2.7.1/articles/installation.html#install-python-dependencies)
[https://camplab.net/sctk/v2.7.1/articles/installation.html#python-and-reticulate](https://camplab.net/sctk/v2.7.1/articles/installation.html#python-and-reticulate)

Best,
Yichen

**Comment by joshua-d-campbell** [comment] 2022-09-27 14:14
Hi @Dragonlongzhilin, was this able to solve your problem? If so, we will close this issue.

**Closed** 2023-01-19 22:04 UTC
